name: Lesaforrit
description: Lestrarapp fyrir krakka.

version: 1.2.0+11

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  bloc: ^7.2.0
  animated_text_kit: ^4.2.1
  audioplayers: ^5.1.0
  connectivity_plus: ^4.0.2
  cupertino_icons: ^1.0.4
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.0
  flutter_spinkit: ^5.1.0
  hydrated_bloc: ^7.1.0
  # icon_shadow: ^1.0.1
  # imagebutton: ^0.0.6
  # modal_progress_hud: ^0.1.3
  path_provider: ^2.0.5
  provider: ^6.0.1
  random_color: ^1.0.5
  rflutter_alert: ^2.0.4
  speech_to_text: ^6.1.0
  flutter_sound_lite: ^8.5.0
  http: ^1.1.0
  flutter_cache_manager: ^3.3.0
  webview_cookie_manager: ^2.0.6
  google_speech: ^3.0.0
  sound_stream:
    git:
      url: https://github.com/alli959/flutter-sound-stream.git
  amplify_flutter: ^1.4.1
  amplify_datastore: ^1.4.1
  amplify_auth_cognito: ^1.4.1
  amplify_api: ^1.4.0
  amplify_storage_s3: ^1.4.0
  change_app_package_name: ^1.1.0
  audio_session: ^0.1.10
  just_audio: ^0.9.30
  dropdown_button2: ^2.3.9
  aws_common: ^0.6.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  auto_size_text: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/sound/
    - assets/soundLevelTwo/
    - assets/soundLevelTwo/long/
    - assets/soundLevelThree/short/
    - assets/soundLevelThree/long/
    - assets/icons/
    - assets/icons/woman_speaking_icon.ico
    - assets/icons/woman_speaking.png
    - assets/Schools.json
    - assets/Schools-reverse.json
    - assets/Schools-reverse-arr.json

  fonts:
    - family: Metropolis
      fonts:
        - asset: fonts/Metropolis-Black.otf
        - asset: fonts/Metropolis-Bold.otf
        - asset: fonts/Metropolis-ExtraBold.otf
        - asset: fonts/Metropolis-ExtraLight.otf
        - asset: fonts/Metropolis-Light.otf
        - asset: fonts/Metropolis-Medium.otf
        - asset: fonts/Metropolis-Regular.otf
        - asset: fonts/Metropolis-RegularItalic.otf
        - asset: fonts/Metropolis-SemiBold.otf
        - asset: fonts/Metropolis-Thin.otf
    - family: MyCustomFlutterApp
      fonts:
        - asset: assets/icons/MyCustomFlutterApp.ttf

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_logo.png"
