# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

# fastlane/Fastfile

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Google Play Beta track"
  lane :beta do
    gradle(task: "clean assembleRelease")
    upload_to_play_store(track: 'beta')
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
  aab_path = File.expand_path('../../build/app/outputs/bundle/release/app-release.aab', __FILE__)
  UI.message("AAB Path: #{aab_path}")
  if File.exist?(aab_path)
    upload_to_play_store(
      track: 'production',
      aab: aab_path,
      version_code: '12'
    )
  else
    UI.error("AAB file not found at #{aab_path}")
  end
end
