# .github/workflows/android_deploy.yml

name: Android Deployment

on:
  push:
    branches:
      - main  # Trigger deployment on pushes to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2  # Check out the repository content

     # Create key.properties file
    - name: Create key.properties
      run: |
        echo "${{ secrets.KEY_PROPERTIES }}" > android/key.properties

    # Decode and save the keystore file
    - name: Decode Keystore
      run: |
      echo "${{ secrets.ENCODED_KEYSTORE }}" | base64 --decode > android/upload-keystore.jks



    - name: List contents of the android directory
      run: ls -la android/
    
    - name: Create amplifyconfiguration.dart
      env:
        AMPLIFY_CONFIGURATION: ${{ secrets.AMPLIFY_CONFIGURATION }}
      run: |
        echo "$AMPLIFY_CONFIGURATION" > lib/amplifyconfiguration.dart

    - name: Set up JDK 11  # Java Development Kit setup for Android builds
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Setup Flutter  # Set up a specific version of Flutter
      uses: subosito/flutter-action@v1
      with:
        flutter-version: '3.13.7'

    - name: Get Flutter dependencies  # Fetch all necessary Flutter packages
      run: flutter pub get

    - name: Build APK  # Build the APK from your Flutter project
      run: flutter build appbundle --release

    - name: Build and upload to Google Play  # Use Fastlane to deploy the APK to Google Play Store
      run: |
        fastlane beta  # You can change this to `fastlane deploy` for production deployment
      env:
        SUPPLY_JSON_KEY_DATA: ${{ secrets.SUPPLY_JSON_KEY_DATA }}  # Ensure this secret is set in your repository settings


