name: Android Deployment

on:
  push:
    branches:
      - main  # Trigger deployment on pushes to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2  # Check out the repository content

    # Decode and save the keystore file
    - name: Decode Keystore
      run: |
        echo "${{ secrets.ENCODED_KEYSTORE }}" | base64 --decode > android/upload-keystore.jks

    # Create key.properties file
    - name: Create key.properties
      run: |
        echo "keyAlias=prod" > android/key.properties
        echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
        echo "storePassword=${{ secrets.STORE_PASSWORD }}" >> android/key.properties
        echo "storeFile=../upload-keystore.jks" >> android/key.properties

    - name: Create Service Account JSON in Assets
      run: |
        echo '${{ secrets.SUPPLY_JSON_KEY_DATA }}' > ./assets/graphite-flare-324114-285b1cf5c32b.json
        
    - name: Create Service Account JSON for Deployment
      run: |
        echo '${{ secrets.ANDROID_DEPLOY_KEY }}' > ./assets/deploy-key.json
        
    - name : List contents of the assets directory
      run: ls -la assets/

    - name: List contents of the android directory
      run: ls -la android/
    
    - name: Create amplifyconfiguration.dart
      env:
        AMPLIFY_CONFIGURATION: ${{ secrets.AMPLIFY_CONFIGURATION }}
      run: |
        echo "$AMPLIFY_CONFIGURATION" > lib/amplifyconfiguration.dart

    - name: Set up JDK 11  # Java Development Kit setup for Android builds
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Setup Flutter  # Set up a specific version of Flutter
      uses: subosito/flutter-action@v1
      with:
        flutter-version: '3.13.7'

    - name: Get Flutter dependencies  # Fetch all necessary Flutter packages
      run: flutter pub get

    - name: Build APK  # Build the APK from your Flutter project
      run: flutter build appbundle --release

    - name: Build and upload to Google Play
      working-directory: ./android
      run: |
        fastlane deploy aab:../build/app/outputs/bundle/release/app-release.aab version_code:12 version_name:1.3.1
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/assets/deploy-key.json
        SUPPLY_JSON_KEY_DATA: ${{ secrets.ANDROID_DEPLOY_KEY }}
