name: iOS Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2.3"

      - name: Install Flutter
        run: |
          brew install flutter

      - name: Install dependencies
        run: |
          brew install node
          npm install -g yarn
          yarn install

      - name: Prepare for Flutter build
        run: |
          cd ios
          flutter pub get
          flutter precache --ios
          flutter clean
          flutter build ios --release --no-codesign
          cd ..

      - name: Install Fastlane
        run: |
          cd ios
          gem install fastlane -NV
          bundle install
          cd ..

      - name: Build and deploy to TestFlight
        env:
          FASTLANE_USER: ${{ secrets.APPLE_ID }}
          API_KEY_ID: ${{ secrets.API_KEY_ID }}
          ISSUER_ID: ${{ secrets.ISSUER_ID }}
          API_KEY_SECRET: ${{ secrets.API_KEY_SECRET }}
        run: |
          cd ios
          fastlane beta
