name: iOS Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create amplifyconfiguration.dart
        env:
          AMPLIFY_CONFIGURATION: ${{ secrets.AMPLIFY_CONFIGURATION }}
        run: |
          echo "$AMPLIFY_CONFIGURATION" > lib/amplifyconfiguration.dart

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2.3"

      - name: Clear Derived Data
        run: rm -rf ~/Library/Developer/Xcode/DerivedData/

      - name: Install Flutter
        run: |
          brew install flutter

      - name: Install dependencies
        run: |
          brew install node
          npm install -g yarn
          yarn install

      - name: Flutter pub get
        run: flutter pub get

      - name: Prepare for Flutter build
        run: |
          flutter precache --ios
          flutter clean
          flutter build ios --release --no-codesign --verbose

      - name: Install and setup CocoaPods
        run: |
          sudo gem install cocoapods
          pod setup
          cd ios
          pod install
          cd ..

      - name: Install Fastlane
        run: |
          gem install fastlane -NV
          cd ios
          bundle install
          cd ..

      - name: Build and deploy to TestFlight
        env:
          FASTLANE_USER: ${{ secrets.APPLE_ID }}
          API_KEY_ID: ${{ secrets.API_KEY_ID }}
          ISSUER_ID: ${{ secrets.ISSUER_ID }}
          API_KEY_SECRET: ${{ secrets.API_KEY_SECRET }}
        run: |
          cd ios
          fastlane beta
